import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mubtaath/core/bloc/language_cubit.dart';
import 'package:mubtaath/core/bloc/room_status_cubit.dart';
import 'package:mubtaath/core/theme/theme.dart';
import 'package:mubtaath/router.dart';
import 'package:mubtaath/splash_cubit.dart';

// Generated by `flutter gen-l10n` — regenerate after editing ARB files.
import 'package:mubtaath/core/l10n/app_localizations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor:          Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      // Bottom Android navigation bar matches the app background (light).
      systemNavigationBarColor:          AppColors.background,
      systemNavigationBarIconBrightness: Brightness.dark,
      systemNavigationBarDividerColor:   AppColors.background,
    ),
  );

  // ── Firebase / FCM push notifications: DISABLED ─────────────────────────────
  // Intentionally removed: no google-services.json is configured, and the
  // firebase-messaging GMS integration crashed the app on Android 15 startup
  // (PushMessagingRegistrarChimeraProxy — "NetworkCapability out of range").
  // In-app notifications still work over Reverb (WebSocket). To restore push:
  // add firebase_core/firebase_messaging back to pubspec.yaml + a real
  // google-services.json, then re-add the init block here.

  runApp(const MubtaathApp());
}

// ─────────────────────────────────────────────────────────────────────────────

class MubtaathApp extends StatelessWidget {
  const MubtaathApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => SplashCubit()),
        BlocProvider(create: (_) => LanguageCubit()),
        BlocProvider(create: (_) => RoomStatusCubit()),
      ],
      child: BlocBuilder<LanguageCubit, Locale>(
        builder: (context, locale) {
          return MaterialApp.router(
            routerConfig: appRouter,
            title: 'مبتعث',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            locale: locale,
            localizationsDelegates: AppLocalizations.localizationsDelegates,
            supportedLocales:       AppLocalizations.supportedLocales,
          );
        },
      ),
    );
  }
}
