import 'dart:async';
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mubtaath/core/auth_notifier.dart';
import 'package:mubtaath/core/bloc/language_cubit.dart';
import 'package:mubtaath/core/bloc/room_status_cubit.dart';
import 'package:mubtaath/core/services/dio_client.dart';
import 'package:mubtaath/core/services/secure_storage_service.dart';
import 'package:mubtaath/core/theme/theme.dart';
import 'package:mubtaath/router.dart';
import 'package:mubtaath/splash_cubit.dart';

// Generated by `flutter gen-l10n` — regenerate after editing ARB files.
import 'package:mubtaath/core/l10n/app_localizations.dart';

// ── FCM background message handler ─────────────────────────────────────────
// Must be a top-level function — runs in a separate isolate when the app is
// killed or backgrounded. The OS renders the notification automatically on the
// high-importance channel declared in AndroidManifest.
@pragma('vm:entry-point')
Future<void> _onBackgroundMessage(RemoteMessage message) async {
  await Firebase.initializeApp();
}

// ── High-importance channel so pushes pop as heads-up banners WITH sound ────
// Without an explicit high-importance channel Android files pushes silently in
// the tray ("بشكل خفي جدا"). This id must match the manifest default channel
// meta-data so background/killed messages use it too.
final FlutterLocalNotificationsPlugin _fcmLocalNotifications =
    FlutterLocalNotificationsPlugin();

// One channel per selectable tone. A notification channel's sound is IMMUTABLE
// after creation, so offering several tones means several channels, each bound
// to a bundled raw sound (android/app/src/main/res/raw/tone_*). The backend
// targets one by its id (android.notification.channel_id); the id also feeds the
// manifest default channel so background/killed messages use a real sound too.
// General push channels — stable ids (kept from the previous build so FCM
// notifications are NOT dropped on phones that haven't updated yet). Max
// importance = heads-up banner. Sound plays on the notification stream; if the
// user keeps notification volume at 0 it's silent — that's a device setting,
// separate from delivery. Prayer/adhan (a LOCAL notification, so no channel
// mismatch) is what routes through the alarm stream — see PrayerNotificationService.
const AndroidNotificationChannel _fcmChannel = AndroidNotificationChannel(
  'high_importance_channel',
  'إشعارات مبتعث',
  description: 'إشعارات عامة من التطبيق',
  importance: Importance.max,
  playSound: true,
);

const List<AndroidNotificationChannel> _fcmToneChannels = [
  _fcmChannel,
  AndroidNotificationChannel(
    'high_importance_chime', 'إشعارات (نغمة رنين)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_chime'),
  ),
  AndroidNotificationChannel(
    'high_importance_bell', 'إشعارات (جرس)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_bell'),
  ),
  AndroidNotificationChannel(
    'high_importance_ping', 'إشعارات (تنبيه)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_ping'),
  ),
  AndroidNotificationChannel(
    'high_importance_marimba', 'إشعارات (ماريمبا)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_marimba'),
  ),
];

Future<void> _initFcmLocalNotifications() async {
  const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
  const darwinInit = DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  await _fcmLocalNotifications.initialize(
    const InitializationSettings(android: androidInit, iOS: darwinInit),
    // Payload is JSON-encoded (see _showForegroundNotification) so a single
    // string can carry both the legacy `type` and the newer actionType/
    // actionTarget tap-target fields through flutter_local_notifications'
    // single-string payload.
    onDidReceiveNotificationResponse: (resp) {
      final raw = resp.payload;
      if (raw == null || raw.isEmpty) return;
      try {
        _routeFromNotificationData(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {
        // Pre-upgrade payloads were a bare type string — fall back to that.
        _routeByType(raw);
      }
    },
  );
  final android = _fcmLocalNotifications.resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin>();
  for (final ch in _fcmToneChannels) {
    await android?.createNotificationChannel(ch);
  }
}

// Foreground pushes: Android does NOT auto-display them, so we render one on the
// SAME channel the backend targeted (which carries the admin's chosen tone) —
// otherwise a push arriving while the app is open is completely invisible.
void _showForegroundNotification(RemoteMessage message) {
  final n = message.notification;
  if (n == null) return;
  final channelId = n.android?.channelId ?? _fcmChannel.id;
  final ch = _fcmToneChannels.firstWhere(
    (c) => c.id == channelId,
    orElse: () => _fcmChannel,
  );
  _fcmLocalNotifications.show(
    n.hashCode,
    n.title,
    n.body,
    NotificationDetails(
      android: AndroidNotificationDetails(
        ch.id,
        ch.name,
        channelDescription: ch.description,
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        sound: ch.sound,
        icon: '@mipmap/ic_launcher',
      ),
      iOS: const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
      ),
    ),
    payload: jsonEncode({
      'type':         message.data['type'],
      'actionType':   message.data['actionType'],
      'actionTarget': message.data['actionTarget'],
    }),
  );
}

// ── Route on FCM payload type (notification tap) ───────────────────────────
void _handleMessageNavigation(RemoteMessage message) {
  _routeFromNotificationData(message.data);
}

// Shared by both tap paths: FCM's native system-tray tap (RemoteMessage.data,
// background/terminated) and flutter_local_notifications' tap on a push we
// rendered ourselves while the app was foregrounded (JSON-decoded payload —
// see _showForegroundNotification). Admin-configured tap-target takes
// priority — 'page' pushes a named app route, 'room' opens that room
// directly. Falls back to the machine-readable `type` used by auto-generated
// notifications (report replies, status changes, ...).
void _routeFromNotificationData(Map<String, dynamic> data) {
  final actionType   = data['actionType'] as String?;
  final actionTarget = data['actionTarget'] as String?;
  if ((actionType == 'page' || actionType == 'room') &&
      actionTarget != null &&
      actionTarget.isNotEmpty) {
    appRouter.push(actionType == 'room' ? '/room/$actionTarget' : actionTarget);
    return;
  }
  _routeByType(data['type'] as String?);
}

void _routeByType(String? type) {
  switch (type) {
    case 'report_reply':
    case 'report_status':
    case 'report_resolved':
      appRouter.push('/support');
    case 'account_suspended':
      suspendedNotifier.value = true;
      authNotifier.value = false;
    default:
      break;
  }
}

// ── Upload the device FCM token to the backend (when logged in) ────────────
Future<void> _uploadFcmToken(String token) async {
  final authToken = await SecureStorageService.readAuthToken();
  if (authToken == null) return; // not logged in yet — skip
  try {
    await appDio.post('/users/me/push-token', data: {'fcm_token': token});
  } catch (_) {
    // Non-fatal — retried on next launch or token refresh.
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor:          Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      // Bottom Android navigation bar matches the app background (light).
      systemNavigationBarColor:          AppColors.background,
      systemNavigationBarIconBrightness: Brightness.dark,
      systemNavigationBarDividerColor:   AppColors.background,
    ),
  );

  // ── Firebase / FCM init ─────────────────────────────────────────────────────
  // Wrapped in try-catch so a missing/failed config never blocks app startup.
  // Push works once google-services.json (Android) / GoogleService-Info.plist
  // (iOS + APNs key) are present. In-app notifications also run over Reverb.
  var firebaseReady = false;
  try {
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (_) {
    // Firebase not available — push disabled, app continues normally.
  }

  runApp(const MubtaathApp());

  // Deliberately NOT awaited before runApp(): permission dialogs and APNs/FCM
  // registration are OS/network round-trips that can stall for a long time
  // (subscribeToTopic in particular hangs if the device's APNs token hasn't
  // registered yet) — none of that may ever gate the first frame again.
  if (firebaseReady) {
    unawaited(_setupFcmMessaging());
  }
}

Future<void> _setupFcmMessaging() async {
  FirebaseMessaging.onBackgroundMessage(_onBackgroundMessage);

  // Register the high-importance channel + local-notification plugin so
  // foreground pushes can be shown as heads-up banners with sound.
  await _initFcmLocalNotifications();

  await FirebaseMessaging.instance.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );

  // The admin dashboard broadcasts push notifications via FCM TOPIC
  // messaging (topic "all" for every user) — a topic send only reaches
  // devices that have explicitly subscribed to it, so every install must
  // subscribe here regardless of login state.
  try {
    await FirebaseMessaging.instance.subscribeToTopic('all');
  } catch (_) {
    // Non-fatal — retried on next launch.
  }

  final initial = await FirebaseMessaging.instance.getInitialMessage();
  if (initial != null) _handleMessageNavigation(initial);

  FirebaseMessaging.instance.getToken().then((t) {
    if (t != null) _uploadFcmToken(t);
  });
  FirebaseMessaging.instance.onTokenRefresh.listen(_uploadFcmToken);
  // Foreground: DISPLAY the push (Android won't auto-show it) so it's never
  // silently swallowed. Tap-to-navigate happens from the notification tap or
  // onMessageOpenedApp — not on arrival, so we never yank the user mid-use.
  FirebaseMessaging.onMessage.listen(_showForegroundNotification);
  FirebaseMessaging.onMessageOpenedApp.listen(_handleMessageNavigation);
}

// ─────────────────────────────────────────────────────────────────────────────

class MubtaathApp extends StatelessWidget {
  const MubtaathApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => SplashCubit()),
        BlocProvider(create: (_) => LanguageCubit()),
        BlocProvider(create: (_) => RoomStatusCubit()),
      ],
      child: BlocBuilder<LanguageCubit, Locale>(
        builder: (context, locale) {
          return MaterialApp.router(
            routerConfig: appRouter,
            title: 'مبتعث',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            locale: locale,
            localizationsDelegates: AppLocalizations.localizationsDelegates,
            supportedLocales:       AppLocalizations.supportedLocales,
          );
        },
      ),
    );
  }
}
