import 'dart:async';
import 'dart:convert';
import 'dart:ui' show PlatformDispatcher;

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mubtaath/core/auth_notifier.dart';
import 'package:mubtaath/core/bloc/language_cubit.dart';
import 'package:mubtaath/core/bloc/room_status_cubit.dart';
import 'package:mubtaath/core/services/dio_client.dart';
import 'package:mubtaath/core/services/secure_storage_service.dart';
import 'package:mubtaath/core/services/log_service.dart';
import 'package:mubtaath/core/theme/theme.dart';
import 'package:mubtaath/router.dart';
import 'package:mubtaath/splash_cubit.dart';

// Generated by `flutter gen-l10n` — regenerate after editing ARB files.
import 'package:mubtaath/core/l10n/app_localizations.dart';

// ── Push-registration diagnostics ──────────────────────────────────────────
// A snapshot of what happened during FCM/APNs setup, surfaced on-device by
// long-pressing the app version in Settings. Lets an iOS push failure be
// inspected without a debug console: if `apnsToken` is NULL the device never
// registered with APNs (a signing / provisioning-profile issue); if the APNs
// token is present but `fcmToken` is NULL/error, it's a Firebase-side issue.
class PushDiagnostics {
  static bool    firebaseReady = false;
  static String? permission;
  static String? apnsToken;
  static String? fcmToken;
  static String? error;

  static String _short(String? t) => t == null
      ? 'NULL'
      : '${t.substring(0, t.length < 12 ? t.length : 12)}… (len ${t.length})';

  static String summary() =>
      'Firebase init: ${firebaseReady ? "ready ✓" : "NOT ready ✗"}\n'
      'Notif permission: ${permission ?? "-"}\n'
      'APNs token: ${_short(apnsToken)}\n'
      'FCM token: ${_short(fcmToken)}\n'
      'Error: ${error ?? "none"}';
}

// ── FCM background message handler ─────────────────────────────────────────
// Must be a top-level function — runs in a separate isolate when the app is
// killed or backgrounded. The OS renders the notification automatically on the
// high-importance channel declared in AndroidManifest.
@pragma('vm:entry-point')
Future<void> _onBackgroundMessage(RemoteMessage message) async {
  await Firebase.initializeApp();
}

// ── High-importance channel so pushes pop as heads-up banners WITH sound ────
// Without an explicit high-importance channel Android files pushes silently in
// the tray ("بشكل خفي جدا"). This id must match the manifest default channel
// meta-data so background/killed messages use it too.
final FlutterLocalNotificationsPlugin _fcmLocalNotifications =
    FlutterLocalNotificationsPlugin();

// One channel per selectable tone. A notification channel's sound is IMMUTABLE
// after creation, so offering several tones means several channels, each bound
// to a bundled raw sound (android/app/src/main/res/raw/tone_*). The backend
// targets one by its id (android.notification.channel_id); the id also feeds the
// manifest default channel so background/killed messages use a real sound too.
// General push channels — stable ids (kept from the previous build so FCM
// notifications are NOT dropped on phones that haven't updated yet). Max
// importance = heads-up banner. Sound plays on the notification stream; if the
// user keeps notification volume at 0 it's silent — that's a device setting,
// separate from delivery. Prayer/adhan (a LOCAL notification, so no channel
// mismatch) is what routes through the alarm stream — see PrayerNotificationService.
const AndroidNotificationChannel _fcmChannel = AndroidNotificationChannel(
  'high_importance_channel',
  'إشعارات مبتعث',
  description: 'إشعارات عامة من التطبيق',
  importance: Importance.max,
  playSound: true,
);

const List<AndroidNotificationChannel> _fcmToneChannels = [
  _fcmChannel,
  AndroidNotificationChannel(
    'high_importance_chime', 'إشعارات (نغمة رنين)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_chime'),
  ),
  AndroidNotificationChannel(
    'high_importance_bell', 'إشعارات (جرس)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_bell'),
  ),
  AndroidNotificationChannel(
    'high_importance_ping', 'إشعارات (تنبيه)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_ping'),
  ),
  AndroidNotificationChannel(
    'high_importance_marimba', 'إشعارات (ماريمبا)',
    importance: Importance.max, playSound: true,
    sound: RawResourceAndroidNotificationSound('tone_marimba'),
  ),
];

Future<void> _initFcmLocalNotifications() async {
  const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
  const darwinInit = DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  await _fcmLocalNotifications.initialize(
    const InitializationSettings(android: androidInit, iOS: darwinInit),
    // Payload is JSON-encoded (see _showForegroundNotification) so a single
    // string can carry both the legacy `type` and the newer actionType/
    // actionTarget tap-target fields through flutter_local_notifications'
    // single-string payload.
    onDidReceiveNotificationResponse: (resp) {
      final raw = resp.payload;
      if (raw == null || raw.isEmpty) return;
      try {
        _routeFromNotificationData(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {
        // Pre-upgrade payloads were a bare type string — fall back to that.
        _routeByType(raw);
      }
    },
  );
  final android = _fcmLocalNotifications.resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin>();
  for (final ch in _fcmToneChannels) {
    await android?.createNotificationChannel(ch);
  }
}

// Foreground pushes: Android does NOT auto-display them, so we render one on the
// SAME channel the backend targeted (which carries the admin's chosen tone) —
// otherwise a push arriving while the app is open is completely invisible.
void _showForegroundNotification(RemoteMessage message) {
  final n = message.notification;
  if (n == null) return;
  final channelId = n.android?.channelId ?? _fcmChannel.id;
  final ch = _fcmToneChannels.firstWhere(
    (c) => c.id == channelId,
    orElse: () => _fcmChannel,
  );
  _fcmLocalNotifications.show(
    n.hashCode,
    n.title,
    n.body,
    NotificationDetails(
      android: AndroidNotificationDetails(
        ch.id,
        ch.name,
        channelDescription: ch.description,
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        sound: ch.sound,
        icon: '@mipmap/ic_launcher',
      ),
      iOS: const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
      ),
    ),
    payload: jsonEncode({
      'type':         message.data['type'],
      'actionType':   message.data['actionType'],
      'actionTarget': message.data['actionTarget'],
    }),
  );
}

// ── Route on FCM payload type (notification tap) ───────────────────────────
void _handleMessageNavigation(RemoteMessage message) {
  _routeFromNotificationData(message.data);
}

// The `actionTarget` in a push payload is server-supplied, so it's never
// pushed as a raw route path. A 'page' target must be one of these known
// static routes; a 'room' target must look like a real room id (UUID).
// Anything else is dropped (the notification still shows, it just doesn't
// deep-link on tap) — a malformed/hostile payload can't navigate the app
// to an arbitrary or crafted route.
const _pushAllowedPageRoutes = <String>{
  '/home', '/notifications', '/student-guide', '/profile',
  '/prayer-times', '/qibla', '/support', '/settings',
};

// Strict UUID shape — no nested quantifiers, so no ReDoS risk.
final _roomIdPattern = RegExp(
  r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
);

// Shared by both tap paths: FCM's native system-tray tap (RemoteMessage.data,
// background/terminated) and flutter_local_notifications' tap on a push we
// rendered ourselves while the app was foregrounded (JSON-decoded payload —
// see _showForegroundNotification). Admin-configured tap-target takes
// priority — 'page' pushes a named app route, 'room' opens that room
// directly. Falls back to the machine-readable `type` used by auto-generated
// notifications (report replies, status changes, ...).
void _routeFromNotificationData(Map<String, dynamic> data) {
  final actionType   = data['actionType'] as String?;
  final actionTarget = data['actionTarget'] as String?;

  if (actionType == 'room' &&
      actionTarget != null &&
      _roomIdPattern.hasMatch(actionTarget)) {
    appRouter.push('/room/$actionTarget');
    return;
  }
  if (actionType == 'page' &&
      actionTarget != null &&
      _pushAllowedPageRoutes.contains(actionTarget)) {
    appRouter.push(actionTarget);
    return;
  }
  _routeByType(data['type'] as String?);
}

void _routeByType(String? type) {
  switch (type) {
    case 'report_reply':
    case 'report_status':
    case 'report_resolved':
      appRouter.push('/support');
    case 'account_suspended':
      suspendedNotifier.value = true;
      authNotifier.value = false;
    default:
      break;
  }
}

// ── Upload the device FCM token to the backend (when logged in) ────────────
Future<void> _uploadFcmToken(String token) async {
  final authToken = await SecureStorageService.readAuthToken();
  if (authToken == null) return; // not logged in yet — skip
  try {
    await appDio.post('/users/me/push-token', data: {'fcm_token': token});
  } catch (_) {
    // Non-fatal — retried on next launch or token refresh.
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Global uncaught-error capture → dashboard logs (fatal) ──────────────
  // FlutterError.onError covers framework/build errors; PlatformDispatcher
  // covers uncaught async errors. Reporting is best-effort and silent in
  // debug (see LogService) so it never affects the running app.
  final priorFlutterOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    priorFlutterOnError?.call(details); // keep default (debug console) behaviour
    LogService.instance.report(
      level:         'fatal',
      message:       details.exceptionAsString(),
      exceptionType: details.exception.runtimeType.toString(),
      stackTrace:    details.stack?.toString(),
    );
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    LogService.instance.report(
      level:         'fatal',
      message:       error.toString(),
      exceptionType: error.runtimeType.toString(),
      stackTrace:    stack.toString(),
    );
    return true; // reported — don't let it bubble to the default crash handler
  };

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor:          Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      // Bottom Android navigation bar matches the app background (light).
      systemNavigationBarColor:          AppColors.background,
      systemNavigationBarIconBrightness: Brightness.dark,
      systemNavigationBarDividerColor:   AppColors.background,
    ),
  );

  // ── Firebase / FCM init ─────────────────────────────────────────────────────
  // Wrapped in try-catch so a missing/failed config never blocks app startup.
  // Push works once google-services.json (Android) / GoogleService-Info.plist
  // (iOS + APNs key) are present. In-app notifications also run over Reverb.
  var firebaseReady = false;
  try {
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (_) {
    // Firebase not available — push disabled, app continues normally.
  }

  runApp(const MubtaathApp());

  PushDiagnostics.firebaseReady = firebaseReady;
  // Deliberately NOT awaited before runApp(): permission dialogs and APNs/FCM
  // registration are OS/network round-trips that can stall for a long time
  // (subscribeToTopic in particular hangs if the device's APNs token hasn't
  // registered yet) — none of that may ever gate the first frame again.
  if (firebaseReady) {
    unawaited(_setupFcmMessaging());
  }
}

Future<void> _setupFcmMessaging() async {
  FirebaseMessaging.onBackgroundMessage(_onBackgroundMessage);

  // Register the high-importance channel + local-notification plugin so
  // foreground pushes can be shown as heads-up banners with sound.
  await _initFcmLocalNotifications();

  final messaging = FirebaseMessaging.instance;

  final permission = await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );
  PushDiagnostics.permission = permission.authorizationStatus.name;

  // ── iOS: wait for the APNs token before touching FCM ────────────────────
  // On Apple platforms FCM cannot mint a token OR subscribe to a topic until
  // the device has registered with APNs and an APNs token is available. If
  // getToken()/subscribeToTopic() run before that (common on a cold launch),
  // they silently no-op — the device never actually subscribes to the "all"
  // topic and never registers a token, so backend pushes never arrive. Local
  // (prayer) notifications don't need APNs, which is why only THOSE worked.
  // Poll briefly for the APNs token, and show foreground pushes natively.
  final isApple = defaultTargetPlatform == TargetPlatform.iOS ||
      defaultTargetPlatform == TargetPlatform.macOS;
  if (isApple) {
    await messaging.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
    // Up to ~10s — first-launch APNs registration can be slow on a cold start.
    String? apnsToken;
    for (var i = 0; i < 20; i++) {
      apnsToken = await messaging.getAPNSToken();
      if (apnsToken != null) break;
      await Future.delayed(const Duration(milliseconds: 500));
    }
    PushDiagnostics.apnsToken = apnsToken;
  }

  // The admin dashboard broadcasts push notifications via FCM TOPIC
  // messaging (topic "all" for every user) — a topic send only reaches
  // devices that have explicitly subscribed to it, so every install must
  // subscribe here regardless of login state.
  try {
    await messaging.subscribeToTopic('all');
  } catch (_) {
    // Non-fatal — retried on next launch.
  }

  final initial = await messaging.getInitialMessage();
  if (initial != null) _handleMessageNavigation(initial);

  // getToken() THROWS on iOS if the APNs token never became available — capture
  // it so the on-device diagnostic can show exactly what failed.
  try {
    final token = await messaging.getToken();
    PushDiagnostics.fcmToken = token;
    if (token != null) _uploadFcmToken(token);
  } catch (e) {
    PushDiagnostics.error = e.toString();
  }

  messaging.onTokenRefresh.listen(_uploadFcmToken);
  // Foreground: DISPLAY the push (Android won't auto-show it) so it's never
  // silently swallowed. Tap-to-navigate happens from the notification tap or
  // onMessageOpenedApp — not on arrival, so we never yank the user mid-use.
  FirebaseMessaging.onMessage.listen(_showForegroundNotification);
  FirebaseMessaging.onMessageOpenedApp.listen(_handleMessageNavigation);
}

// ─────────────────────────────────────────────────────────────────────────────

class MubtaathApp extends StatelessWidget {
  const MubtaathApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => SplashCubit()),
        BlocProvider(create: (_) => LanguageCubit()),
        BlocProvider(create: (_) => RoomStatusCubit()),
      ],
      child: BlocBuilder<LanguageCubit, Locale>(
        builder: (context, locale) {
          return MaterialApp.router(
            routerConfig: appRouter,
            title: 'مبتعث',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            locale: locale,
            localizationsDelegates: AppLocalizations.localizationsDelegates,
            supportedLocales:       AppLocalizations.supportedLocales,
          );
        },
      ),
    );
  }
}
